### ISSUE TITLE
Remove unsafe code?

### ISSUE THREAD

**Issue by egdv** [dertuxmalwieder/yaydl#10]
Rust's most important feature is memory safety and using unsafe removes this feature.

At my forked repo, I have pushed a branch that removed all unsafe code in spankbang.rs and can be used to remove all unsafe code in the project

https://github.com/egdv/yaydl/tree/no-unsafe

**Comment by dertuxmalwieder** [comment]
Do the additional methods make any sense when the unsafe code is removed at all?

**Comment by egdv** [comment]
The additional methods are to allow old unsafe existing code to work alongside the new all safe code. Ideally updating the existing unsafe code, we just replace the global variable static mutable String VIDEO_INFO causing the unsafe requirement, with mutable reference String passed as a method argument declared within main() 

method definition argument:
video_info: &mut String,

fn get_video_info_s(...) shows how it will work with the scraping code. The calling methods will get the updated html value since it's a mutable reference.

**Comment by dertuxmalwieder** [comment]
> The additional methods are to allow old unsafe existing code to work alongside the new all safe code

I'd favor a complete move to safe code, to be honest, `yaydl` is a low-traffic project, chances are that there won't be any new sites contributed by anyone else in the next few hours ... ;-) keeping old code there "for compatibility" makes no sense IMO ...?

**Comment by egdv** [comment]
Yeah, complete move to safe code is likely better. I can just easily comment out not yet updated handlers from handlers.rs then comment in as it gets updated.

**Comment by dertuxmalwieder** [comment]
I'd volunteer to ... help? 😂
(However, not before the weekend, I guess.)

**Comment by egdv** [comment]
All done!

branch = safe-only

https://github.com/egdv/yaydl/tree/safe-only

here's testing results:
mod porndoe;  tested ok
mod spankbang; tested ok
mod vidoza; not tested
mod vimeo; tested ok
mod vivo; not tested
mod voe; not tested
mod watchmdh; watchmdh.to  tested failed same as latest repo
mod xhamster; tested ok
mod youtube; tested failed same as latest repo

**Comment by dertuxmalwieder** [comment]
Awesome.

I - personally - can live with broken porn sites, but they probably attract users. 😏
The broken YouTube mod is *annoying* though. Yet, still not much time ... [the offer in the README is open for you, by the way: if you wish, you can have upstream access - seems to make work much easier for both of us].

Pushed 0.11.1. I took the freedom ;-) to make `get_video_info()` return a bool instead of an empty `Result<Html>` where applicable. Cannot update crates.io, surprisingly - something on this computer behaves *not* the way I'd like it...

Good night, for now.
